####********初级红包任务*******######
#任务ID 1000-1999
#Real  true表示指定金额红包 false表示幸运红包
#Total 任务需要完成多少次
#Fee   红包奖励金额
#Desc  红包任务描述
#Type  红包类型 1:新人指定金额红包 2:新人幸运红包 3:指定金额红包 4:幸运红包
[[CfgPrimaryTasks]]
    ID=1000
	Real=true
	Total=1
	Fee=1.0
	Desc="在任意金币场对局10局"
	Jump=0
	Type=1
[[CfgPrimaryTasks]]
    ID=1001
	Real=true
	Total=1
	Fee=1.0
	Desc="在任意金币场连胜2局"
	Jump=0
	Type=1
[[CfgPrimaryTasks]]
    ID=1002
	Real=true
	Total=1
	Fee=2.0
	Desc="在任意金币场当地主5次"
	Jump=0
	Type=1
[[CfgPrimaryTasks]]
    ID=1003
	Real=true
	Total=1
	Fee=2.0
	Desc="参加一次红包比赛场"
	Jump=0
	Type=1
[[CfgPrimaryTasks]]
    ID=1004
	Real=false
	Total=1
	Fee=1.0
	Desc="购买任意数量的金币"
	Jump=0
	Type=2
[[CfgPrimaryTasks]]
    ID=1005
	Real=true
	Total=1
	Fee=1.0
	Desc="在任意金币场胜利10局"
	Jump=0
	Type=3
[[CfgPrimaryTasks]]
    ID=1006
	Real=true
	Total=1
	Fee=1.0
	Desc="在任意金币场打出3个飞机"
	Jump=0
	Type=3
[[CfgPrimaryTasks]]
    ID=1007
	Real=false
	Total=1
	Fee=1.0
	Desc="在任意金币场打出5个连对"
	Jump=0
	Type=3
[[CfgPrimaryTasks]]
    ID=1008
	Real=true
	Total=1
	Fee=2.0
	Desc="在任意金币场打出3个炸弹"
	Jump=0
	Type=3
[[CfgPrimaryTasks]]
    ID=1009
	Real=false
	Total=1
	Fee=1.0
	Desc="在任意金币场打出3个王炸"
	Jump=0
	Type=4
[[CfgPrimaryTasks]]
    ID=1010
	Real=true
	Total=1
	Fee=1.0
	Desc="在任意金币场当地主10次"
	Jump=0
	Type=3
[[CfgPrimaryTasks]]
    ID=1011
	Real=true
	Total=1
	Fee=1.0
	Desc="在任意金币场抢地主10次"
	Jump=0
	Type=3
[[CfgPrimaryTasks]]
    ID=1012
	Real=true
	Total=1
	Fee=2.0
	Desc="在任意金币场明牌开始10次"
	Jump=0
	Type=3
[[CfgPrimaryTasks]]
    ID=1013
	Real=false
	Total=1
	Fee=1.0
	Desc="购买任意数量的金币"
	Jump=0
	Type=4
[[CfgPrimaryTasks]]
    ID=1014
	Real=false
	Total=1
	Fee=1.0
	Desc="在任意金币场地主身份获胜5局"
	Jump=0
	Type=4
[[CfgPrimaryTasks]]
    ID=1015
	Real=false
	Total=1
	Fee=1.0
	Desc="在任意金币场明牌获胜3次"
	Jump=0
	Type=4
[[CfgPrimaryTasks]]
    ID=1016
	Real=false
	Total=1
	Fee=1.0
	Desc="菜鸟场加倍底分4次"
	Jump=0
	Type=4
####********中级红包任务*******######
[[CfgMiddleTasks]]
    ID=2000
	Real=true
	Total=1
	Fee=1.0
	Desc="在任意金币场打出5个王炸"
	Type=3
	Jump=0
[[CfgMiddleTasks]]
    ID=2001
	Real=true
	Total=1
	Fee=2.0
	Desc="在任意金币场单局打出两个炸弹"
	Type=3
	Jump=0
[[CfgMiddleTasks]]
    ID=2002
	Real=true
	Total=1
	Fee=2.0
	Desc="在任意金币场打出10个连对"
	Type=3
	Jump=0
[[CfgMiddleTasks]]
    ID=2003
	Real=false
	Total=1
	Fee=1.0
	Desc="普通场累计对局10次"
	Type=4
	Jump=0
[[CfgMiddleTasks]]
    ID=2004
	Real=false
	Total=1
	Fee=1.0
	Desc="普通场打出6个顺子"
	Type=4
	Jump=0
[[CfgMiddleTasks]]
    ID=2005
	Real=false
	Total=1
	Fee=1.0
	Desc="普通场加倍底分4次"
	Type=4
	Jump=0
[[CfgMiddleTasks]]
    ID=2006
	Real=false
	Total=1
	Fee=1.0
	Desc="普通场当地主8次"
	Type=4
	Jump=0
[[CfgMiddleTasks]]
    ID=2007
	Real=true
	Total=1
	Fee=2.0
	Desc="普通场叫叫地主6次"
	Type=3
	Jump=0
[[CfgMiddleTasks]]
    ID=2008
	Real=false
	Total=1
	Fee=1.0
	Desc="在任意金币场连胜5局"
	Type=4
	Jump=0
[[CfgMiddleTasks]]
    ID=2009
	Real=false
	Total=1
	Fee=1.0
	Desc="在任意金币场打出8次三带二"
	Type=4
	Jump=0
[[CfgMiddleTasks]]
    ID=2010
	Real=false
	Total=1
	Fee=1.0
	Desc="在任意金币场打出3次四带二"
	Type=4
	Jump=0
[[CfgMiddleTasks]]
    ID=2011
	Real=true
	Total=1
	Fee=2.0
	Desc="在任意金币场以地主的身份获胜10次"
	Type=3
	Jump=0
	
####********高级红包任务*******######
[[CfgHighTasks]]
    ID=3000
	Real=true
	Total=1
	Fee=2.0
	Desc="在任意金币场单局打出两个顺子5次"
	Type=3
	Jump=0
[[CfgHighTasks]]
    ID=3001
	Real=true
	Total=1
	Fee=2.0
	Desc="在任意金币场当地主20次"
	Type=3
	Jump=0
[[CfgHighTasks]]
    ID=3002
	Real=false
	Total=1
	Fee=1.0
	Desc="普通场打出8次三带二"
	Type=4
	Jump=0
[[CfgHighTasks]]
    ID=3003
	Real=false
	Total=1
	Fee=1.0
	Desc="普通场打出3次四带二"
	Type=4
	Jump=0
[[CfgHighTasks]]
    ID=3004
	Real=false
	Total=1
	Fee=1.0
	Desc="在任意金币场连胜8局"
	Type=4
	Jump=0

[[CfgHighTasks]]
    ID=3005
	Real=false
	Total=1
	Fee=1.0
	Desc="普通场明牌开始10次"
	Type=4
	Jump=0
[[CfgHighTasks]]
    ID=3006
	Real=true
	Total=1
	Fee=1.0
	Desc="在任意金币场打出2个春天"
	Type=4
	Jump=0
[[CfgHighTasks]]
    ID=3007
	Real=true
	Total=1
	Fee=5.0
	Desc="在任意金币场明牌获胜5次"
	Type=3
	Jump=0
[[CfgHighTasks]]
    ID=3008
	Real=false
	Total=1
	Fee=2.0
	Desc="普通场加倍底分8次"
	Type=4
	Jump=0
[[CfgHighTasks]]
    ID=3009
	Real=true
	Total=1
	Fee=5.0
	Desc="参与土豪场10次"
	Type=3
	Jump=0
