[[CfgShareTasks]]
    ID=4001
	Real=true
	Total=2
	Fee=1.0
	Desc="连胜两局"
	Info="获得1元"

[[CfgShareTasks]]
    ID=4002
	Real=false
	Total=5
	Fee=1.0
	Desc="打出五个连对"
	Info="获得幸运红包"
[[CfgShareTasks]]
    ID=4003
	Real=true
	Total=3
	Fee=2.0
	Desc="打出三个炸弹"
	Info="获得2元"
[[CfgShareTasks]]
    ID=4004
	Real=false
	Total=1
	Fee=8.0
	Desc="充值10元"
	Info="返利8元"
[[CfgShareTasks]]
    ID=4005
	Real=false
	Total=8
	Fee=8.0
	Desc="普通场当地主8次"
	Info="获得幸运红包"
[[CfgShareTasks]]
    ID=4006
	Real=true
	Total=1
	Fee=80.0
	Desc="充值100元"
	Info="返利80元"
[[CfgShareTasks]]
    ID=4007
	Real=true
	Total=5
	Fee=5.0
	Desc="明牌获胜5次"
	Info="获得5元"
[[CfgShareTasks]]
    ID=4008
	Real=false
	Total=0
	Fee=0.0
	Desc="充值任意金额"
	Info="返利80%"

[[CfgShareCalcMethods]]
    AchieveScope=0
    BackMoney=0.5
    DiffMoney=0.1
[[CfgShareCalcMethods]]
    AchieveScope=50
    BackMoney=1.0
    DiffMoney=0.2
[[CfgShareCalcMethods]]
    AchieveScope=100
    BackMoney=2.0
    DiffMoney=0.5
[[CfgShareCalcMethods]]
    AchieveScope=200
    BackMoney=5.0
    DiffMoney=1.0
[[CfgShareCalcMethods]]
    AchieveScope=500
    BackMoney=8.0
    DiffMoney=2.0
[[CfgShareCalcMethods]]
    AchieveScope=1000
    BackMoney=10.0
    DiffMoney=3.0
[[CfgShareCalcMethods]]
    AchieveScope=2000
    BackMoney=15.0
    DiffMoney=4.0
[[CfgShareCalcMethods]]
    AchieveScope=5000
    BackMoney=20.0
    DiffMoney=5.0
[[CfgShareCalcMethods]]
    AchieveScope=10000
    BackMoney=25.0
    DiffMoney=7.0
[[CfgShareCalcMethods]]
    AchieveScope=20000
    BackMoney=30.0
    DiffMoney=10.0
[[CfgShareCalcMethods]]
    AchieveScope=50000
    BackMoney=35.0
    DiffMoney=15.0
[[CfgShareCalcMethods]]
    AchieveScope=100000
    BackMoney=40.0
    DiffMoney=25.0